### ISSUE TITLE
can you provide ÈFI file for new macOS version 

### ISSUE THREAD

**Issue by cesc1802** [nhoxnho1212/thinkpad-t480-hackintosh#1]
I'm using macOS 10.14.3, but now I want to upgrade it to the new version. can you share me new EFI support it for the modal t480 thinkpad

**Comment by nhoxnho1212** [comment]
now i don't use hackintosh, if u want to upgrade, u can use hacktintool to upgrade kext

**Comment by cesc1802** [comment]
thanks. I'm a beginner Hackintosh. if I want to upgrade, just update kext, right?

**Comment by nhoxnho1212** [comment]
yuh, i think it work

**Comment by cesc1802** [comment]
thanks for help me
